version: '3.7'

services:
  app:
    build:
      context: .
    ports:
      - 8070:8070

    environment:
      - CORS_ALLOWED_ORIGINS=http://localhost:8080,http://0.0.0.0:8080,http://127.0.0.1:8080
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/moove_one
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_NAME=moove_one
      - DB_PASSWORD=postgres
      - DEBUG=False
      - SECRET_KEY=SECRET_KEY
      - BROKER_URL=redis
      - CELERY_RESULT_BACKEND=redis
    volumes:
      - ./:/app
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py generate_data
             python3 manage.py runserver 0.0.0.0:8070"
    networks:
      - app-network
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=prodapt
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - app-network
    restart: unless-stopped

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
  celery:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - CELERY_BROKER_URL=redis
      - CELERY_RESULT_BACKEND=redis
    command: celery -A app worker -l info
    volumes:
      - ./:/app
    networks:
      - app-network
    depends_on:
      - app
      - redis

  celery-beat:
    build:
      context: ./
    command: celery -A app beat -l info
    volumes:
      - ./:/app
    environment:
      - CELERY_BROKER_URL=redis
      - CELERY_RESULT_BACKEND=redis
    networks:
      - app-network
    depends_on:
      - app
      - redis
      - celery

networks:
  app-network:
    driver: bridge

volumes:
  postgres:
  celery:
  celery-beat:
  redis_data: