# Generated by Django 4.1.2 on 2022-10-15 17:13

import uuid

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('weather_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Weather type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_time_forecasted', models.DateTimeField(blank=True, null=True, verbose_name='Date Time Forecasted')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
