# Generated by Django 3.1.2 on 2022-10-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherforecast',
            name='weather_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Weather type'),
        ),
    ]
